---
- hosts: localhost
  tasks:
    - name: install httpd package
      yum:
        name: httpd
        state: installed 
      notify:
        - start server
  handlers:
    - name: start server
      systemd:
        name: httpd
        state: restarted
