---
- name: sending an email
  hosts: localhost
  tasks:
   - name: send email
     mail:
      host: "smtp.gmail.com"
      port: 587
      from: "vijaybiztalk2010@gmail.com"
      password: "biztalk2010"
      to: "anil.devops86@gmail.com"
      subject: ansible
      body: "hello from ansible "
      secure: starttls
    
